<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class AlternatifSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('alternatif')->insert([
            [
                'alternatif' => 1,
                'kondisi_rumah' => 2,
                'kelayakan' => 4,
                'status_pernikahan' => 2,
                'jumlah_anak' => 5,
                'jumlah_tanggungan' => 2,
                'umur_yang_bekerja' => 3,
                'phk' => 1,
            ],
            [
                'alternatif' => 2,
                'kondisi_rumah' => 3,
                'kelayakan' => 3,
                'status_pernikahan' => 3,
                'jumlah_anak' => 3,
                'jumlah_tanggungan' => 3,
                'umur_yang_bekerja' => 3,
                'phk' => 2,
            ],
            [
                'alternatif' => 3,
                'kondisi_rumah' => 1,
                'kelayakan' => 2,
                'status_pernikahan' => 3,
                'jumlah_anak' => 1,
                'jumlah_tanggungan' => 1,
                'umur_yang_bekerja' => 4,
                'phk' => 1,
            ],
            [
                'alternatif' => 4,
                'kondisi_rumah' => 2,
                'kelayakan' => 1,
                'status_pernikahan' => 1,
                'jumlah_anak' => 2,
                'jumlah_tanggungan' => 4,
                'umur_yang_bekerja' => 2,
                'phk' => 2,
            ],
            [
                'alternatif' => 5,
                'kondisi_rumah' => 3,
                'kelayakan' => 4,
                'status_pernikahan' => 3,
                'jumlah_anak' => 4,
                'jumlah_tanggungan' => 3,
                'umur_yang_bekerja' => 1,
                'phk' => 2,
            ],
            [
                'alternatif' => 6,
                'kondisi_rumah' => 1,
                'kelayakan' => 3,
                'status_pernikahan' => 2,
                'jumlah_anak' => 1,
                'jumlah_tanggungan' => 4,
                'umur_yang_bekerja' => 3,
                'phk' => 2,
            ],
            [
                'alternatif' => 7,
                'kondisi_rumah' => 2,
                'kelayakan' => 3,
                'status_pernikahan' => 3,
                'jumlah_anak' => 2,
                'jumlah_tanggungan' => 4,
                'umur_yang_bekerja' => 2,
                'phk' => 1,
            ],
            [
                'alternatif' => 8,
                'kondisi_rumah' => 2,
                'kelayakan' => 2,
                'status_pernikahan' => 3,
                'jumlah_anak' => 5,
                'jumlah_tanggungan' => 2,
                'umur_yang_bekerja' => 1,
                'phk' => 1,
            ],
            [
                'alternatif' => 9,
                'kondisi_rumah' => 3,
                'kelayakan' => 1,
                'status_pernikahan' => 3,
                'jumlah_anak' => 4,
                'jumlah_tanggungan' => 1,
                'umur_yang_bekerja' => 3,
                'phk' => 2,
            ],
            [
                'alternatif' => 10,
                'kondisi_rumah' => 2,
                'kelayakan' => 4,
                'status_pernikahan' => 2,
                'jumlah_anak' => 5,
                'jumlah_tanggungan' => 3,
                'umur_yang_bekerja' => 2,
                'phk' => 1,
            ],
            [
                'alternatif' => 11,
                'kondisi_rumah' => 1,
                'kelayakan' => 2,
                'status_pernikahan' => 1,
                'jumlah_anak' => 5,
                'jumlah_tanggungan' => 2,
                'umur_yang_bekerja' => 1,
                'phk' => 2,
            ],
            [
                'alternatif' => 12,
                'kondisi_rumah' => 2,
                'kelayakan' => 3,
                'status_pernikahan' => 3,
                'jumlah_anak' => 4,
                'jumlah_tanggungan' => 1,
                'umur_yang_bekerja' => 2,
                'phk' => 1,
            ],
            [
                'alternatif' => 13,
                'kondisi_rumah' => 3,
                'kelayakan' => 1,
                'status_pernikahan' => 1,
                'jumlah_anak' => 1,
                'jumlah_tanggungan' => 1,
                'umur_yang_bekerja' => 2,
                'phk' => 2,
            ],
            [
                'alternatif' => 14,
                'kondisi_rumah' => 2,
                'kelayakan' => 2,
                'status_pernikahan' => 3,
                'jumlah_anak' => 2,
                'jumlah_tanggungan' => 3,
                'umur_yang_bekerja' => 3,
                'phk' => 1,
            ],
            [
                'alternatif' => 15,
                'kondisi_rumah' => 1,
                'kelayakan' => 3,
                'status_pernikahan' => 2,
                'jumlah_anak' => 5,
                'jumlah_tanggungan' => 4,
                'umur_yang_bekerja' => 4,
                'phk' => 1,
            ],
            [
                'alternatif' => 16,
                'kondisi_rumah' => 1,
                'kelayakan' => 4,
                'status_pernikahan' => 1,
                'jumlah_anak' => 3,
                'jumlah_tanggungan' => 2,
                'umur_yang_bekerja' => 3,
                'phk' => 1,
            ],
            [
                'alternatif' => 17,
                'kondisi_rumah' => 3,
                'kelayakan' => 3,
                'status_pernikahan' => 2,
                'jumlah_anak' => 2,
                'jumlah_tanggungan' => 1,
                'umur_yang_bekerja' => 2,
                'phk' => 1,
            ],
            [
                'alternatif' => 18,
                'kondisi_rumah' => 2,
                'kelayakan' => 2,
                'status_pernikahan' => 3,
                'jumlah_anak' => 3,
                'jumlah_tanggungan' => 2,
                'umur_yang_bekerja' => 1,
                'phk' => 2,
            ],
            [
                'alternatif' => 19,
                'kondisi_rumah' => 3,
                'kelayakan' => 1,
                'status_pernikahan' => 2,
                'jumlah_anak' => 2,
                'jumlah_tanggungan' => 3,
                'umur_yang_bekerja' => 4,
                'phk' => 2,
            ],
            [
                'alternatif' => 20,
                'kondisi_rumah' => 3,
                'kelayakan' => 4,
                'status_pernikahan' => 1,
                'jumlah_anak' => 4,
                'jumlah_tanggungan' => 2,
                'umur_yang_bekerja' => 2,
                'phk' => 1,
            ],
        ]);
    }
}
