<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WargaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('warga')->insert([
            [
                'id_kk' => 1,
                'id_rt' => 1,
                'nama_warga' => 'Andi Sutrisno',
                'alamat' => 'Jalan Simpang Danau Meninjau Selatan No. 1, Malang',
                'no_telepon' => '081234567890',
                'NIK' => '327601040111001',
                'tanggal_lahir' => '1975-01-01',
                'jenis_kelamin' => 'L',
                'foto_warga' => 'https://example.com/photos/andi_sutrisno.jpg',
                'jenis_warga' => 'Lokal',
                'agama' => 'Islam',
            ],
            [
                'id_kk' => 2,
                'id_rt' => 3,
                'nama_warga' => 'Siti Aminah',
                'alamat' => 'Jl. Merdeka No. 2',
                'no_telepon' => '081234567891',
                'NIK' => '3201234567890002',
                'tanggal_lahir' => '1985-02-02',
                'jenis_kelamin' => 'P',
                'foto_warga' => 'https://example.com/photos/siti_aminah.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Islam',
            ],
            [
                'id_kk' => 3,
                'id_rt' => 2,
                'nama_warga' => 'Budi Santoso',
                'alamat' => 'Jl. Kemerdekaan No. 3',
                'no_telepon' => '081234567892',
                'NIK' => '3201234567890003',
                'tanggal_lahir' => '1970-03-03',
                'jenis_kelamin' => 'L',
                'foto_warga' => 'https://example.com/photos/budi_santoso.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Kristen',
            ],
            [
                'id_kk' => 4,
                'id_rt' => 2,
                'nama_warga' => 'Ani Setiani',
                'alamat' => 'Jl. Kemerdekaan No. 4',
                'no_telepon' => '081234567893',
                'NIK' => '3201234567890004',
                'tanggal_lahir' => '1990-04-04',
                'jenis_kelamin' => 'P',
                'foto_warga' => 'https://example.com/photos/ani_setiani.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Islam',
            ],
            [
                'id_kk' => 5,
                'id_rt' => 1,
                'nama_warga' => 'Dewi Sartika',
                'alamat' => 'Jl. Harmoni No. 5',
                'no_telepon' => '081234567894',
                'NIK' => '3201234567890005',
                'tanggal_lahir' => '1988-05-05',
                'jenis_kelamin' => 'P',
                'foto_warga' => 'https://example.com/photos/dewi_sartika.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Islam',
            ],
            [
                'id_kk' => 6,
                'id_rt' => 2,
                'nama_warga' => 'Eko Purwanto',
                'alamat' => 'Jl. Harmoni No. 6',
                'no_telepon' => '081234567895',
                'NIK' => '3201234567890006',
                'tanggal_lahir' => '1983-06-06',
                'jenis_kelamin' => 'L',
                'foto_warga' => 'https://example.com/photos/eko_purwanto.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Kristen',
            ],
            [
                'id_kk' => 7,
                'id_rt' => 3,
                'nama_warga' => 'Fajar Nugroho',
                'alamat' => 'Jl. Harmoni No. 7',
                'no_telepon' => '081234567896',
                'NIK' => '3201234567890007',
                'tanggal_lahir' => '1987-07-07',
                'jenis_kelamin' => 'L',
                'foto_warga' => 'https://example.com/photos/fajar_nugroho.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Islam',
            ],
            [
                'id_kk' => 8,
                'id_rt' => 3,
                'nama_warga' => 'Gina Lestari',
                'alamat' => 'Jl. Harmoni No. 8',
                'no_telepon' => '081234567897',
                'NIK' => '3201234567890008',
                'tanggal_lahir' => '1992-08-08',
                'jenis_kelamin' => 'P',
                'foto_warga' => 'https://example.com/photos/gina_lestari.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Islam',
            ],
            [
                'id_kk' => 9,
                'id_rt' => 1,
                'nama_warga' => 'Hariyanto',
                'alamat' => 'Jl. Sejahtera No. 9',
                'no_telepon' => '081234567898',
                'NIK' => '3201234567890009',
                'tanggal_lahir' => '1981-09-09',
                'jenis_kelamin' => 'L',
                'foto_warga' => 'https://example.com/photos/hariyanto.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Hindu',
            ],
            [
                'id_kk' => 10,
                'id_rt' => 1,
                'nama_warga' => 'Ika Nuraini',
                'alamat' => 'Jl. Sejahtera No. 10',
                'no_telepon' => '081234567899',
                'NIK' => '3201234567890010',
                'tanggal_lahir' => '1989-10-10',
                'jenis_kelamin' => 'P',
                'foto_warga' => 'https://example.com/photos/ika_nuraini.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Islam',
            ],
            [
                'id_kk' => 11,
                'id_rt' => 2,
                'nama_warga' => 'Joko Susilo',
                'alamat' => 'Jl. Sejahtera No. 11',
                'no_telepon' => '081234567900',
                'NIK' => '3201234567890011',
                'tanggal_lahir' => '1978-11-11',
                'jenis_kelamin' => 'L',
                'foto_warga' => 'https://example.com/photos/joko_susilo.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Buddha',
            ],
            [
                'id_kk' => 12,
                'id_rt' => 3,
                'nama_warga' => 'Kartika Sari',
                'alamat' => 'Jl. Sejahtera No. 12',
                'no_telepon' => '081234567901',
                'NIK' => '3201234567890012',
                'tanggal_lahir' => '1991-12-12',
                'jenis_kelamin' => 'P',
                'foto_warga' => 'https://example.com/photos/kartika_sari.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Islam',
            ],
            [
                'id_kk' => 13,
                'id_rt' => 1,
                'nama_warga' => 'Luthfi Rahman',
                'alamat' => 'Jl. Sejahtera No. 13',
                'no_telepon' => '081234567902',
                'NIK' => '3201234567890013',
                'tanggal_lahir' => '1984-01-13',
                'jenis_kelamin' => 'L',
                'foto_warga' => 'https://example.com/photos/luthfi_rahman.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Islam',
            ],
            [
                'id_kk' => 14,
                'id_rt' => 2,
                'nama_warga' => 'Maya Sari',
                'alamat' => 'Jl. Sejahtera No. 14',
                'no_telepon' => '081234567903',
                'NIK' => '3201234567890014',
                'tanggal_lahir' => '1993-02-14',
                'jenis_kelamin' => 'P',
                'foto_warga' => 'https://example.com/photos/maya_sari.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Kristen',
            ],
            [
                'id_kk' => 15,
                'id_rt' => 3,
                'nama_warga' => 'Nanda Putra',
                'alamat' => 'Jl. Sejahtera No. 15',
                'no_telepon' => '081234567904',
                'NIK' => '3201234567890015',
                'tanggal_lahir' => '1986-03-15',
                'jenis_kelamin' => 'L',
                'foto_warga' => 'https://example.com/photos/nanda_putra.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Hindu',
            ],
            [
                'id_kk' => 16,
                'id_rt' => 1,
                'nama_warga' => 'Olivia Putri',
                'alamat' => 'Jl. Sejahtera No. 16',
                'no_telepon' => '081234567905',
                'NIK' => '3201234567890016',
                'tanggal_lahir' => '1994-04-16',
                'jenis_kelamin' => 'P',
                'foto_warga' => 'https://example.com/photos/olivia_putri.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Islam',
            ],
            [
                'id_kk' => 17,
                'id_rt' => 2,
                'nama_warga' => 'Prasetyo Adi',
                'alamat' => 'Jl. Sejahtera No. 17',
                'no_telepon' => '081234567906',
                'NIK' => '3201234567890017',
                'tanggal_lahir' => '1982-05-17',
                'jenis_kelamin' => 'L',
                'foto_warga' => 'https://example.com/photos/prasetyo_adi.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Islam',
            ],
            [
                'id_kk' => 18,
                'id_rt' => 3,
                'nama_warga' => 'Qoriatul Aini',
                'alamat' => 'Jl. Sejahtera No. 18',
                'no_telepon' => '081234567907',
                'NIK' => '3201234567890018',
                'tanggal_lahir' => '1995-06-18',
                'jenis_kelamin' => 'P',
                'foto_warga' => 'https://example.com/photos/qoriatul_aini.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Kristen',
            ],
            [
                'id_kk' => 19,
                'id_rt' => 1,
                'nama_warga' => 'Rangga Putra',
                'alamat' => 'Jl. Sejahtera No. 19',
                'no_telepon' => '081234567908',
                'NIK' => '3201234567890019',
                'tanggal_lahir' => '1980-07-19',
                'jenis_kelamin' => 'L',
                'foto_warga' => 'https://example.com/photos/rangga_putra.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Islam',
            ],
            [
                'id_kk' => 20,
                'id_rt' => 2,
                'nama_warga' => 'Sari Dewi',
                'alamat' => 'Jl. Sejahtera No. 20',
                'no_telepon' => '081234567909',
                'NIK' => '3201234567890020',
                'tanggal_lahir' => '1996-08-20',
                'jenis_kelamin' => 'P',
                'foto_warga' => 'https://example.com/photos/sari_dewi.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Islam',
            ],
            [
                'id_kk' => 21,
                'id_rt' => 2,
                'nama_warga' => 'Erci Sukaesi',
                'alamat' => 'Jl. Sejahtera No. 35',
                'no_telepon' => '081234587892',
                'NIK' => '3201254368970020',
                'tanggal_lahir' => '1996-08-20',
                'jenis_kelamin' => 'P',
                'foto_warga' => 'https://example.com/photos/Erci_Sukaesi.jpg',
                'jenis_warga' => 'Pendatang',
                'agama' => 'Islam',
            ],
        ]);
    }
}