<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WargaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('warga')->insert([
            [
                'id_kk' => 1,
                'id_rt' => 1,
                'nama_warga' => 'Ahmad Fauzi',
                'alamat' => 'Jl. Merdeka No. 1',
                'no_telepon' => '081234567890',
                'email' => 'ahmad.fauzi@example.com',
                'NIK' => '1234567890123456',
                'tanggal_lahir' => '1985-06-15',
                'jenis_kelamin' => 'L',
                'status_kawin' => 'Kawin',
                'pekerjaan' => 'Guru',
                'foto_warga' => 'https://example.com/photos/ahmad_fauzi.jpg',
                'transportasi' => 'Motor',
                'status_kepemilikan_rumah' => 'Milik Sendiri',
                'status_perkawinan' => 'Kawin',
                'sumber_air_bersih' => 'PDAM',
                'token_listrik' => '1234567890',
                'penerangan_rumah' => 'Listrik',
                'luas_bangunan' => '70m2',
                'pengeluaran_bulanan' => 3000000.00,
                'jumlah_anggota_keluarga' => '4',
                'penghasilan' => '5000000',
                'tanggungan' => '2',
                'jenis_warga' => 'Tetap',
            ],
            [
                'id_kk' => 2,
                'id_rt' => 1,
                'nama_warga' => 'Siti Aminah',
                'alamat' => 'Jl. Kartini No. 2',
                'no_telepon' => '082345678901',
                'email' => 'siti.aminah@example.com',
                'NIK' => '2345678901234567',
                'tanggal_lahir' => '1990-07-20',
                'jenis_kelamin' => 'P',
                'status_kawin' => 'Belum Kawin',
                'pekerjaan' => 'Dokter',
                'foto_warga' => 'https://example.com/photos/siti_aminah.jpg',
                'transportasi' => 'Mobil',
                'status_kepemilikan_rumah' => 'Sewa',
                'status_perkawinan' => 'Belum Kawin',
                'sumber_air_bersih' => 'Sumur',
                'token_listrik' => '0987654321',
                'penerangan_rumah' => 'Listrik',
                'luas_bangunan' => '100m2',
                'pengeluaran_bulanan' => 5000000.00,
                'jumlah_anggota_keluarga' => '2',
                'penghasilan' => '10000000',
                'tanggungan' => '1',
                'jenis_warga' => 'Pendatang',
            ],
            [
                'id_kk' => 3,
                'id_rt' => 2,
                'nama_warga' => 'Budi Santoso',
                'alamat' => 'Jl. Diponegoro No. 3',
                'no_telepon' => '083456789012',
                'email' => 'budi.santoso@example.com',
                'NIK' => '3456789012345678',
                'tanggal_lahir' => '1975-08-25',
                'jenis_kelamin' => 'L',
                'status_kawin' => 'Duda',
                'pekerjaan' => 'Pengusaha',
                'foto_warga' => 'https://example.com/photos/budi_santoso.jpg',
                'transportasi' => 'Motor',
                'status_kepemilikan_rumah' => 'Milik Sendiri',
                'status_perkawinan' => 'Cerai',
                'sumber_air_bersih' => 'PDAM',
                'token_listrik' => '1122334455',
                'penerangan_rumah' => 'Listrik',
                'luas_bangunan' => '150m2',
                'pengeluaran_bulanan' => 8000000.00,
                'jumlah_anggota_keluarga' => '3',
                'penghasilan' => '15000000',
                'tanggungan' => '1',
                'jenis_warga' => 'Tetap',
            ],
            [
                'id_kk' => 4,
                'id_rt' => 2,
                'nama_warga' => 'Rina Kurniawati',
                'alamat' => 'Jl. Sudirman No. 4',
                'no_telepon' => '084567890123',
                'email' => 'rina.kurniawati@example.com',
                'NIK' => '4567890123456789',
                'tanggal_lahir' => '1980-09-30',
                'jenis_kelamin' => 'P',
                'status_kawin' => 'Janda',
                'pekerjaan' => 'Pegawai Negeri',
                'foto_warga' => 'https://example.com/photos/rina_kurniawati.jpg',
                'transportasi' => 'Motor',
                'status_kepemilikan_rumah' => 'Milik Sendiri',
                'status_perkawinan' => 'Cerai',
                'sumber_air_bersih' => 'Sumur',
                'token_listrik' => '2233445566',
                'penerangan_rumah' => 'Listrik',
                'luas_bangunan' => '80m2',
                'pengeluaran_bulanan' => 4000000.00,
                'jumlah_anggota_keluarga' => '2',
                'penghasilan' => '7000000',
                'tanggungan' => '1',
                'jenis_warga' => 'Pendatang',
            ],
            [
                'id_kk' => 5,
                'id_rt' => 3,
                'nama_warga' => 'Agus Wijaya',
                'alamat' => 'Jl. Gatot Subroto No. 5',
                'no_telepon' => '085678901234',
                'email' => 'agus.wijaya@example.com',
                'NIK' => '5678901234567890',
                'tanggal_lahir' => '1970-10-10',
                'jenis_kelamin' => 'L',
                'status_kawin' => 'Kawin',
                'pekerjaan' => 'Petani',
                'foto_warga' => 'https://example.com/photos/agus_wijaya.jpg',
                'transportasi' => 'Sepeda',
                'status_kepemilikan_rumah' => 'Milik Sendiri',
                'status_perkawinan' => 'Kawin',
                'sumber_air_bersih' => 'PDAM',
                'token_listrik' => '3344556677',
                'penerangan_rumah' => 'Listrik',
                'luas_bangunan' => '60m2',
                'pengeluaran_bulanan' => 2000000.00,
                'jumlah_anggota_keluarga' => '5',
                'penghasilan' => '3000000',
                'tanggungan' => '3',
                'jenis_warga' => 'Tetap',
            ],
        ]);
    }
}
